apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
  namespace: cka
spec:
  containers:
  - image: nginx
    name: container1
    resources: {}
  - name: container2
    image: busybox
    args:
    - sleep
    - "4800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
